[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pythoncpptemplate"
version = "0.0.1"
dependencies = []

[project.scripts]
myFunction = "src.pythoncpptemplate.myFunction:myFunction"